import yaml


# This file hijacks the order in which Python parses the file in order to create user-configurable items.
class C(object):
    USERNAME = ''
    PASSWORD = ''

    ELASTICSEARCH_BASE_URL = ''

    ELASTICSEARCH_CREDENTIALS = None
    ELASTICSEARCH_USE_SSL = True
    ELASTICSEARCH_VERIFY_SSL = False

    # Below are items that the user should not be allowed to set via configuration file
    # This section only exists so IDEs won't complain about missing variables.
    TESLA_API_VEHICLE_KEYWORD_ID = ''
    TESLA_API_VEHICLE_KEYWORD_VEHICLE_ID = ''
    TESLA_API_VEHICLE_KEYWORD_VIN = ''
    TESLA_API_VEHICLE_KEYWORD_DISPLAY_NAME = ''
    TESLA_API_VEHICLE_KEYWORD_OPTION_CODES = ''
    TESLA_API_VEHICLE_KEYWORD_COLOR = ''
    TESLA_API_VEHICLE_KEYWORD_ACCESS_TYPE = ''
    TESLA_API_VEHICLE_KEYWORD_TOKENS = ''
    TESLA_API_VEHICLE_KEYWORD_STATE = ''
    TESLA_API_VEHICLE_KEYWORD_IN_SERVICE = ''
    TESLA_API_VEHICLE_KEYWORD_ID_S = ''
    TESLA_API_VEHICLE_KEYWORD_CALENDAR_ENABLED = ''
    TESLA_API_VEHICLE_KEYWORD_API_VERSION = ''
    TESLA_API_VEHICLE_KEYWORD_BACKSEAT_TOKEN = ''
    TESLA_API_VEHICLE_KEYWORD_BACKSEAT_TOKEN_UPDATED_AT = ''
    TESLA_API_VEHICLE_KEYWORD_COMMAND_SIGNING = ''

    TESLA_API_VEHICLE_DATA_KEYWORD_ID = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_VEHICLE_ID = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_VIN = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_DISPLAY_NAME = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_OPTION_CODES = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_COLOR = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_ACCESS_TYPE = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_TOKENS = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_STATE = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_IN_SERVICE = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_ID_S = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_CALENDAR_ENABLED = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_API_VERSION = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_BACKSEAT_TOKEN = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_BACKSEAT_TOKEN_UPDATED_AT = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_COMMAND_SIGNING = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_USER_ID = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_CHARGE_STATE = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_CLIMATE_STATE = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_DRIVE_STATE = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_GUI_SETTINGS = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_VEHICLE_CONFIG = ''
    TESLA_API_VEHICLE_DATA_KEYWORD_VEHICLE_STATE = ''

    TESLA_API_VEHICLE_STATE_VALUE_ASLEEP = ''
    TESLA_API_VEHICLE_STATE_VALUE_ONLINE = ''


# This takes the contents of config.yaml and creds.yaml and updates the values in class C
for configuration_filename in ['config.yaml', 'creds.yaml']:
    _fin = open(configuration_filename, 'r')
    yams = _fin.read()
    _fin.close()
    yaml_config = yaml.load(yams, Loader=yaml.SafeLoader)
    for k, v in yaml_config.items():
        setattr(C, k, v)
    del _fin


# Finally, set the constant values where the user can no longer update them
# Vehicles
C.TESLA_API_VEHICLE_KEYWORD_ID = 'id'
C.TESLA_API_VEHICLE_KEYWORD_VEHICLE_ID = 'vehicle_id'
C.TESLA_API_VEHICLE_KEYWORD_VIN = 'vin'
C.TESLA_API_VEHICLE_KEYWORD_DISPLAY_NAME = 'display_name'
C.TESLA_API_VEHICLE_KEYWORD_OPTION_CODES = 'option_codes'
C.TESLA_API_VEHICLE_KEYWORD_COLOR = 'color'
C.TESLA_API_VEHICLE_KEYWORD_ACCESS_TYPE = 'access_type'
C.TESLA_API_VEHICLE_KEYWORD_TOKENS = 'tokens'
C.TESLA_API_VEHICLE_KEYWORD_STATE = 'state'
C.TESLA_API_VEHICLE_KEYWORD_IN_SERVICE = 'in_service'
C.TESLA_API_VEHICLE_KEYWORD_ID_S = 'id_s'
C.TESLA_API_VEHICLE_KEYWORD_CALENDAR_ENABLED = 'calendar_enabled'
C.TESLA_API_VEHICLE_KEYWORD_API_VERSION = 'api_version'
C.TESLA_API_VEHICLE_KEYWORD_BACKSEAT_TOKEN = 'backseat_token'
C.TESLA_API_VEHICLE_KEYWORD_BACKSEAT_TOKEN_UPDATED_AT = 'backseat_token_updated_at'
C.TESLA_API_VEHICLE_KEYWORD_COMMAND_SIGNING = 'command_signing'

C.TESLA_API_VEHICLE_STATE_VALUE_ASLEEP = 'asleep'
C.TESLA_API_VEHICLE_STATE_VALUE_ONLINE = 'online'

# Vehicle state
C.TESLA_API_VEHICLE_DATA_KEYWORD_ID = 'id'
C.TESLA_API_VEHICLE_DATA_KEYWORD_VEHICLE_ID = 'vehicle_id'
C.TESLA_API_VEHICLE_DATA_KEYWORD_VIN = 'vin'
C.TESLA_API_VEHICLE_DATA_KEYWORD_DISPLAY_NAME = 'display_name'
C.TESLA_API_VEHICLE_DATA_KEYWORD_OPTION_CODES = 'option_codes'
C.TESLA_API_VEHICLE_DATA_KEYWORD_COLOR = 'color'
C.TESLA_API_VEHICLE_DATA_KEYWORD_ACCESS_TYPE = 'access_type'
C.TESLA_API_VEHICLE_DATA_KEYWORD_TOKENS = 'tokens'
C.TESLA_API_VEHICLE_DATA_KEYWORD_STATE = 'state'
C.TESLA_API_VEHICLE_DATA_KEYWORD_IN_SERVICE = 'in_service'
C.TESLA_API_VEHICLE_DATA_KEYWORD_ID_S = 'id_s'
C.TESLA_API_VEHICLE_DATA_KEYWORD_CALENDAR_ENABLED = 'calendar_enabled'
C.TESLA_API_VEHICLE_DATA_KEYWORD_API_VERSION = 'api_version'
C.TESLA_API_VEHICLE_DATA_KEYWORD_BACKSEAT_TOKEN = 'backseat_token'
C.TESLA_API_VEHICLE_DATA_KEYWORD_BACKSEAT_TOKEN_UPDATED_AT = 'backseat_token_updated_at'
C.TESLA_API_VEHICLE_DATA_KEYWORD_COMMAND_SIGNING = 'command_signing'
C.TESLA_API_VEHICLE_DATA_KEYWORD_USER_ID = 'user_id'
C.TESLA_API_VEHICLE_DATA_KEYWORD_CHARGE_STATE = 'charge_state'
C.TESLA_API_VEHICLE_DATA_KEYWORD_CLIMATE_STATE = 'climate_state'
C.TESLA_API_VEHICLE_DATA_KEYWORD_DRIVE_STATE = 'drive_state'
C.TESLA_API_VEHICLE_DATA_KEYWORD_GUI_SETTINGS = 'gui_settings'
C.TESLA_API_VEHICLE_DATA_KEYWORD_VEHICLE_CONFIG = 'vehicle_config'
C.TESLA_API_VEHICLE_DATA_KEYWORD_VEHICLE_STATE = 'vehicle_state'
